version: "3"

services:
  backend:
    build:
      context: ./backend/springboot-standalone
      dockerfile: Dockerfile-spring-boot
    ports:
      - "8080:8080"
    depends_on: 
      - postgresdb

  postgresdb:
    build:
      context: ./backend/database
      dockerfile: Dockerfile-postgres
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    
