CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Postagens" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" character varying(32) NOT NULL,
    "Conteudo" character varying(1024) NOT NULL,
    "Autor" character varying(16) NOT NULL,
    CONSTRAINT "PK_Postagens" PRIMARY KEY ("Id")
);

START TRANSACTION;

CREATE TABLE "Comentarios" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PostagemId" bigint NOT NULL,
    "Conteudo" character varying(128) NOT NULL,
    "Autor" character varying(16) NOT NULL,
    CONSTRAINT "PK_Comentarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comentarios_Postagens_PostagemId" FOREIGN KEY ("PostagemId") REFERENCES "Postagens" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ComentariosPostagens" (
    "PostagemId" bigint NOT NULL,
    "ComentarioId" bigint NOT NULL,
    "PostagemId1" bigint NULL,
    "ComentarioId1" bigint NULL,
    CONSTRAINT "PK_ComentariosPostagens" PRIMARY KEY ("PostagemId", "ComentarioId"),
    CONSTRAINT "FK_ComentariosPostagens_Comentarios_ComentarioId1" FOREIGN KEY ("ComentarioId1") REFERENCES "Comentarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ComentariosPostagens_Postagens_PostagemId1" FOREIGN KEY ("PostagemId1") REFERENCES "Postagens" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Comentarios_PostagemId" ON "Comentarios" ("PostagemId");

CREATE INDEX "IX_ComentariosPostagens_ComentarioId1" ON "ComentariosPostagens" ("ComentarioId1");

CREATE INDEX "IX_ComentariosPostagens_PostagemId1" ON "ComentariosPostagens" ("PostagemId1");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210131233317_blog', '5.0.2');

INSERT INTO "Postagens" ("Titulo", "Conteudo", "Autor")
VALUES ('ABC da Amazônia: Pato no tucupi', 'Comer pato é coisa comum no Pará, e o pato no tucupi está sempre na mesa em dias de festa. É considerado o prato que não pode faltar no círio de Nazaré, uma das maiores festas religiosas do país. Existem muitos criadores de pato no Pará, alguns apuram a raça a partir de vários cruzamentos, inclusive com patos selvagens, a carne é escura e firme preparado com vários temperos, o pato é assado cortado em pedaços e mergulhado no tucupi, um caldo amarelo extraído da mandioca. O último toque vem do jambu, planta picante que provoca ligeira dormência na boca e que faz parte de muitas receitas da cozinha paraense.', 'TV Globo');

COMMIT;

